---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minetest
  name: minetest
  namespace: default
spec:
  ports:
    - name: minetest
      port: 30000
      protocol: UDP
  selector:
    app: minetest
  type: NodePort
