# Two backend pods, one always failing
# and another one returning OK response
# Slowcooker is used to generate traffic
# that will be routed via traffic split
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: backend
    spec:
      containers:
      - args:
        - terminus
        - --h1-server-port=8080
        - --response-text=backend1
        image: buoyantio/bb:v0.0.6
        name: backend
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: failing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failing
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: failing
    spec:
      containers:
      - args:
        - terminus
        - --h1-server-port=8080
        - --response-text=failing
        - --percent-failure=100
        image: buoyantio/bb:v0.0.6
        name: failing
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: failing-svc
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: failing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow-cooker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slow-cooker
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: slow-cooker
    spec:
      containers:
      - args:
        - -c
        - |
          sleep 5 # wait for pods to start
          /slow_cooker/slow_cooker http://backend-svc:8080
        command:
        - /bin/sh
        image: buoyantio/slow_cooker:1.3.0
        name: slow-cooker
        ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: slow-cooker
spec:
  ports:
  - name: metrics
    port: 9999
    targetPort: 9999
  selector:
    app: slow-cooker
---
