apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rpagliuca/meu-minikube.git
    targetRevision: HEAD
    path: argocd-managed/linkerd-control-plane
    helm:
      fileParameters:
      - name: identityTrustAnchorsPEM
        path: argocd-managed/linkerd-control-plane/ca.crt
      - name: identity.issuer.tls.crtPEM
        path: argocd-managed/linkerd-control-plane/issuer.crt
      - name: identity.issuer.tls.keyPEM
        path: argocd-managed/linkerd-control-plane/issuer.key
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
