apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: mario
spec:
 rules:
   - host: mario.my-minikube.com
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: mario
               port:
                 number: 8080
